services:
  data_ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    container_name: data_ingest
    restart: on-failure
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=machine_x
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_USER=admin
      - OPENSEARCH_PASSWORD=admin
    volumes:
      - ./data:/app/data
    depends_on:
      mosquitto:
        condition: service_healthy
      postgres:
        condition: service_healthy
      #opensearch:
        #condition: service_healthy

  opensearch_prepare:
    container_name: opensearch_prepare
    build:
      context: .
      dockerfile: Dockerfile.prepare
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
    - OPENSEARCH_HOST=opensearch
    - OPENSEARCH_PORT=9200
    - OPENSEARCH_USE_SSL=FALSE
    #- OPENSEARCH_USER=admin
    #- OPENSEARCH_PASSWORD=admin
    # This service is for a one-off task, so we don't need it to restart unless it fails
    restart: "on-failure"

  data_gen:
    build:
      context: .
      dockerfile: Dockerfile.simulate
    container_name: data_gen
    restart: on-failure
    environment:
      - MQTT_BROKER_HOST=mosquitto
    depends_on:
      mosquitto:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test/topic", "-m", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: machine_x
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      #- OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
      #- OPENSEARCH_INITIAL_ADMIN_USERNAME=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f --silent --show-error --head http://localhost:9200/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5

  kibana:
    image: opensearchproject/opensearch-dashboards:2.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - plugins.security.enabled=false
      #- OPENSEARCH_USERNAME=admin
      #- OPENSEARCH_PASSWORD=admin
      - server.name=kibana
    depends_on:
      opensearch:
        condition: service_healthy

volumes:
  postgres-data:
  opensearch-data:
