#Use a lightweight Python base image
FROM python:3.9-slim

#Set working directory
WORKDIR /app

#Install dependencies from the requirements.txt file
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#Copy the application code
COPY sql2os.py .

#Run the script to continuously ingest data
CMD ["python", "sql2os.py"]